// Code generated by sqlc. DO NOT EDIT.

package storage

import (
	"time"
)

type Category struct {
	ID        int32
	Name      string
	CreatedAt time.Time
	UpdatedAt time.Time
}

type Notification struct {
	ID            int32
	ObservationID int32
	CreatedAt     time.Time
	UpdatedAt     time.Time
	Comment       string
	Link          string
}

type Observation struct {
	ID        int64
	Link      string
	SpeciesID int64
	CreatedAt time.Time
	UpdatedAt time.Time
}

type ObservationState struct {
	ID            int32
	ObservationID int32
	VolunteerID   int64
	StateID       int64
	Comment       string
	CreatedAt     time.Time
	UpdatedAt     time.Time
}

type Species struct {
	ID         int32
	Name       string
	CommonName string
	CreatedAt  time.Time
	UpdatedAt  time.Time
}

type State struct {
	ID         int32
	CategoryID int32
	Name       string
	CreatedAt  time.Time
	UpdatedAt  time.Time
}

type Volunteer struct {
	ID        int32
	Fname     string
	Lname     string
	RoleID    int32
	CreatedAt time.Time
	UpdatedAt time.Time
}
